name: ASP.NET Core 5.0 - Desafio Toro

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      CAMINHO_PROJETO_TESTES: ./src/ToroChallenge.Models.Tests/ToroChallenge.Models.Tests.csproj
      CAMINHO_PROJETO_WEBAPI: ./src/ToroChallenge.Api
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Executar testes
      run: dotnet test ${{env.CAMINHO_PROJETO_TESTES}} --verbosity minimal
    
    - name: Executar build Api
      run: dotnet build  ${{env.CAMINHO_PROJETO_WEBAPI}} --configuration Release 
    
    - name: Gerar publish Api
      run: dotnet publish  ${{env.CAMINHO_PROJETO_WEBAPI}} -c Release -o app
