name: ASP.NET Core 5.0 - Desafio Toro

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      CAMINHO_PROJETO_TESTES_PAPEL: ./src/Dominio/ToroChallenge.PapelContexto.Domain.Tests/ToroChallenge.PapelContexto.Domain.Tests.csproj
      CAMINHO_PROJETO_TESTES_TRANSFERENCIA: ./src/Dominio/ToroChallenge.PapelTransferencia.Domain.Tests/ToroChallenge.PapelTransferencia.Domain.Tests.csproj
      CAMINHO_PROJETO_WEBAPI: ./src/ToroChallenge.Api
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Executar testes Papel
      run: dotnet test ${{env.CAMINHO_PROJETO_TESTES_PAPEL}} --verbosity minimal
      
    - name: Executar testes Transferencia
      run: dotnet test ${{env.CAMINHO_PROJETO_TESTES_TRANSFERENCIA}} --verbosity minimal
    
    - name: Executar build Api
      run: dotnet build  ${{env.CAMINHO_PROJETO_WEBAPI}} --configuration Release 
    
    - name: Gerar publish Api
      run: dotnet publish  ${{env.CAMINHO_PROJETO_WEBAPI}} -c Release -o app
